app/models.py
from app import db

class Task(db.Model):
    __tablename__ = "task"  # lowercase

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    status = db.Column(db.String(20), default="pending")

class User(db.Model):
    __tablename__ = "user"  # lowercase
    id = db.Column(db.Integer , primary_key=True, autoincrement=True)
    username = db.Column(db.String(100), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)  # bigger for hashed pw

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv
import os
import pymysql
pymysql.install_as_MySQLdb()

db = SQLAlchemy()

def create_app():
    load_dotenv()

    app = Flask(__name__)
    print("DB URI:", os.getenv("DATABASE_URI"))
    print("SECRET_KEY:", os.getenv("SECRET_KEY"))

    app.config['SECRET_KEY'] = os.getenv("SECRET_KEY", "default_secret")
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv("DATABASE_URI")
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False         # fixed type

    db.init_app(app)  # proper initialization

    # Import and register blueprints
    from app.routes.auth import auth_bp
    from app.routes.task import task_bp

    app.register_blueprint(auth_bp)
    app.register_blueprint(task_bp)

    return app

app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for , flash, session
from app.models import User
from app import db

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if user :
            flash('User already Exists', 'danger')
        else:
            new_user = User(username = username , password = password)
            db.session.add(new_user)
            db.session.commit()

            # Log the user in immediately
            session['user'] = username
            flash('Registration successful! You are now logged in.', 'success')
            return redirect(url_for('task.view_task'))
    return render_template('register.html')

@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()

        if user:
            session['user'] = username
            flash('Login Successful', 'success')
            return  redirect(url_for('task.view_task'))
        else:
            flash('Invalid username or password', 'danger')
    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    session.pop('user', None)
    flash('Logged Out', 'info')
    return redirect(url_for('auth.login'))

app/routes/task.py
from flask import Blueprint, render_template, request, redirect, url_for , flash, session
from app import db
from app.models import Task


task_bp = Blueprint('task', __name__)

@task_bp.route('/')
def view_task():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    tasks = Task.query.all()
    return render_template('task.html', tasks = tasks)


@task_bp.route('/add', methods = ["POST"])
def add_task():
    if 'user' not in session:
        return redirect(url_for('auth.login'))

    title = request.form.get('title')
    if title:
        new_task = Task(title = title, status = 'Pending')
        db.session.add(new_task)
        db.session.commit()
        flash('Task added Successfully', 'success')

    return redirect(url_for('task.view_task'))

@task_bp.route('/toggle-status/<int:task_id>', methods = ["POST"])
def toggle_status(task_id):
    task = Task.query.get(task_id)
    if task:
        if task.status == 'Pending':
            task.status = 'Working'
        elif task.status == 'Working':
            task.status = 'Done'
        else:
            task.status = 'Pending'
        db.session.commit()
    return redirect(url_for('task.view_task'))

@task_bp.route('/clear', methods = ['POST'])
def clear_task():
    Task.query.delete()
    db.session.commit()
    flash('All Task cleared', 'info')
    return redirect(url_for('task.view_task'))

app/templates/base.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{%block title %} ToDo App {%endblock%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <h1> My To-Do App</h1>
            <nav>
                <a href="{{url_for('task.view_task')}}">Home</a>
                {% if 'user' in session %}
                    <a href="{{url_for('auth.logout')}}">Logout</a>
                {% else %}
                    <a href="{{url_for('auth.login')}}">Login</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <main class="container">
        {% with messages = get_flashed_messages(with_categories = True) %}
        {% for category, message in messages %}
         <div class = "flash {{category}}">{{message}}</div>
        {%endfor%}
        {%endwith%}
        {% block content %} {%endblock%}
    </main>
    <footer>
        <div class="container">
            <p> &copy; {{2025}} My Flask To-do app</p>
        </div>
    </footer>
</body>
</html>

app/templates/login.html
{%extends "base.html"%}
{% block title %} Login {%endblock%}

{% block content %}
<div class="login-box">
    <h2>Login</h2>
    <form method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
        </div>

        <button type="submit" class="btn">Login</button><br><br>
    </form>
    <form action="{{ url_for('auth.register') }}" method="get">
        <button type="submit" class="btn">Register</button>
    </form>
</div>
{%endblock%}

app/templates/register.html
{% extends "base.html" %}
{% block title %} Login {%endblock%}

{% block content %}
<div class="login-box">
    <h2>Register</h2>
    <form method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
        </div>
        <button type="submit" class="btn">Register</button>
    </form>
</div>
{%endblock%}

app/templates/task.html
{% extends "base.html" %}
{% block title %} Tasks {% endblock %}
{% block content %}
<div class = "task_box">
    <h2>Your Task</h2>
    <form action="{{url_for('task.add_task')}}" method="post" class = "task-form">
        <input type="text" name="title" placeholder="New task" required>
        <button type="submit" class="btn ">Add Task</button>
    </form>
    {% if tasks %}
    <form method="post" action = "{{url_for('task.clear_task')}}">
        <button type="submit" class="btn btn-clear ">Clear All Tasks</button>
    </form>
    <br>
    <table class="task-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Task</th>
                <th>Status</th>
                <th>Change</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{loop.index}}</td>
                <td>{{task.title}}</td>
                <td>
                    <span class = "badge {{task.status|lower}}">{{task.status}}</span>
                </td>
                <td>
                    <form action = "{{ url_for('task.toggle_status', task_id = task.id)}}" method = "POST">
                        <button type="submit" class="btn-small">Next</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No Task yet</p>
    {% endif %}
</div>
{% endblock %}